version: "3.8"

services:
  advanced_ids_app:
    build: .
    container_name: advanced_ids
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    restart: always
    environment:
      - ENV=production
